name: Build and Deploy to GitHub Pages

on:
  push:
    branches: 'main' 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
           BASE_PATH: '/tweet-sentiment-stock-impact'
        run: npm run build

      - name: Check Build Output
        run: ls -R dist/   # Change 'build/' to 'dist/'

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
           path: 'dist/'  # Change 'build/' to 'dist/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: https://niketha-s.github.io/tweet-sentiment-stock-impact/

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
